version: '3.8'

services:
  n8n:
    build: .
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=RESPOND@toronto7tobin
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=e179de6c-27cc-41bf-8ac6-01359942b5a0
      - NODE_FUNCTION_ALLOW_EXTERNAL=pg
      - PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=e179de6c-27cc-41bf-8ac6-01359942b5a0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
